import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "../globals.css";
import { logout } from "./actions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navData = [
  {
    id: 1,
    title: "Home",
    href: "/",
  },
  {
    id: 2,
    title: "Users",
    href: "/users",
  },
  {
    id: 3,
    title: "Posts",
    href: "/posts",
  },
  {
    id: 4,
    title: "Register",
    href: "/register",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-screen w-full flex flex-col items-center space-y-8">
          <nav className="flex items-center justify-center space-x-10 h-10 border-b border-emerald-500">
            {navData.map(({ id, title, href }) => (
              <Link className="font-bold" key={id} href={href}>
                {title}
              </Link>
            ))}
            <form action={logout}>
              <button className="p-2 sm:p-3 rounded-md bg-emerald-600 text-white w-full">
                logout
              </button>
            </form>
          </nav>
          <div className="flex justify-center items-start h-full w-full">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
